{% set version = "1.1.7" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gensa
  version: {{ version|replace("-", "_") }}

source:
  fn: GenSA_1.1.7.tar.gz
  url: https://cran.r-project.org/src/contrib/GenSA_1.1.7.tar.gz
  sha256: 9d99d3d0a4b7770c3c3a6de44206811272d78ab94481713a8c369f7d6ae7b80f

build:
  number: 1005
  # does not build on win
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('fortran') }}    # [not win]
    - {{ compiler('m2w64_c') }}          # [win]
    - {{ compiler('m2w64_cxx') }}          # [win]
    - {{ compiler('m2w64_fortran') }}          # [win]
    - {{ posix }}filesystem          # [win]
    - {{ posix }}make

  host:
    - r-base

  run:
    - r-base
    - {{ native }}gcc-libs           # [win]

test:
  commands:
    - $R -e "library('GenSA')"           # [not win]
    - "\"%R%\" -e \"library('GenSA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=GenSA
  license: GPL-2.0-only
  summary: Performs search for global minimum of a very complex non-linear objective function with a very large number of optima.
  license_family: GPL2

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - lucapinello
    - bgruening
    - mxr-conda
    - bubblyorca

    

