appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: i9QBfFxRsUsOPh3ST802wkgNgdoTl5V9VFDl0H4OuPMolhcTfs+P6saJcNZCsTjLNz28eKZ1Kiv3Wx6eSAOwPwiwkYfnJ1HtWcPfY/ipFEwbrucpk0kO2Dh5BSC3d2nkrhlL8BT5GduQSoIytRHMHpHG7utAqQpxC5y2b0SAb6JJP1Gz1yjYMlOIuTXAIfSIlMxyo/ssKniVloSY0E45GyTIQSLw6RBxAR3VXVDi4gI++7KKgttp2tmxhD0aus52Zv8QHfN1HbXloSistIhVrYwzzsS6hrdVcvvcMyfZ/H5rxEcvgswtyHgixe1vc8Qj1NTQdLIBi9eedjwVUZi6fqOTTjlalVDtupldAny3faZjEuBf697RVbW+kXYTJTmGZ7sK8CSQAv5cO360aPnnH8L+ULkGS/da93IOUIiUylY/50W/Wqph4B2G/aocnUnGlAH+NByTeAqvkudngrRFEZ1TwlB5DRiB8niqLo4Vej4yA2ErE1dAAn9z3T9A9sTM9nCCxXZv7oWBSJ3wO3g0KvGbwlrf0qZOg9EDzUG6rmQBySrjwUpk2hInHkPWP9HyGDpEGLDuJ0cgrOLqSe6/VH8BQx9u3Pi9CA6W7b/KHR6dAygCIBQyYE36IbMV9uEZa4NXweAqttMLCTxX6TA3SbJfesR1F2OiLkV9CnF++lk=
conda_forge_output_validation: true
