travis:
  secure:
    BINSTAR_TOKEN: Fm6zPfBUfotSBj4dIHW1NPOZphl9cH0l6aEXktF0VVNwqrrVk8/qkPYxjo15k3c9/rcI50F/kMGQjel1MigR8hVd34lJfRQBfwkJ03IzOJtNNq3B2qPv68xD5yyGB3Do6bjj6ePjAaPSBvJ9kX40m13xlPcotqwX1C/rDjEsmdBK/lhDjBoPrzpckCsZbgIcTBlXq1X2JKvaP7yzVOLtRH8gA146gV7pGtiC0vIpHLiH4MwMP3atBgi9Z2dhTYiwNa/dm7Tqye3pLe1OIOuJnqJMiDJzCP0Wh8WBXAK9G3jHCkufWc5dOPJ5l2IlgB1U2WvqX3ekkS6nwQDT7pGIn5S3eP7pOE7HmtxIcXwZABXFJeqyL+Vw2XCVt9m1otbzU/gc6Iuzoj42/4mWbe3qUWKBDduslzZh0NvpWi7Ne/WAO5dO6UcfC4MCV2vvgQv7NTWgoUOZbG+JkfrWraJXskc3VFpVXWDdreM5+jPW9TSKutjFmAm1QfJwoPk2jBv4VZaBjvmmfqBPadY/sPro5XTMzUP6wj5+buga5zS8jTQMGiVqUEO97p6+AYciyXp3qwOPw9Si1SZRxgE62srk2hABgWE3lHUvwQ/thXF7TlL3GR/RxwgKgI/iNC+dq9DwZO8yE8FHmqCM9u/oZ6ePUqH+LzV3S8GwiU9hEsH9wis=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
